spring.application.name=gym
spring.datasource.url=jdbc:postgresql://localhost:5432/bdGym
spring.datasource.username=postgres
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

application.security.jwt.secret-key=tH4Dnw3VT8lXX28AZ4cWUAgkGRbvJiVM8bVMmLyYRyY=
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true